---
title: "Exercise 2"
author: "Carilli"
date: '`r format(lubridate::today(), "%B %d, %Y")`'
output: 
  html_document:
    theme: cerulean
    highlight: tango
---

```{r setup, include=FALSE, tidy=TRUE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, warning = FALSE, message = FALSE,
                      options(digits = 3, scipen = 999))
library(tidyverse)
```

```{r 2data}
height_wages <- 
  here::here("data", "heightwage_british_all_multivariate.csv") %>% 
  read_csv() %>% 
  janitor::clean_names() %>% 
  mutate(sex = factor(female, labels = c("male", "female")))
```

### (a)

```{r 2a}
height_wages %>% 
  mutate(across(where(is.numeric), scale)) %>% 
  lm(gwage33 ~ height16 + momed + daded + siblings, .) %>% 
  jtools::summ(digits = 4)
```

### (b)

```{r 2b}
jtools::export_summs(
  height_wages %>% 
  lm(gwage33 ~ sex, .),
  
  height_wages %>% 
  mutate(sex = factor(1 - female, labels = c("male", "female"))) %>% 
  lm(gwage33 ~ sex, .),
  digits = 4
)
```

### (c)


```{r 2c}
height_wages %>% 
  lm(log(gwage33) ~ sex, .) %>% 
  jtools::summ(digits = 4)
```

### (d)

```{r 2d}
height_wages %>% 
  lm(log(gwage33) ~ sex + height33 + height16, .) %>% 
  jtools::summ(digits = 4)
```

### (e)

```{r 2e}
height_wages %>% 
  lm(log(gwage33) ~ sex*height16 + siblings, .) %>% 
  jtools::summ(digits = 4)

height_wages %>% 
  lm(log(gwage33) ~ sex*height16, .) %>% 
  car::linearHypothesis("height16 - sexfemale:height16 = 0")

```


